async (page) => {
  const passed = [];
  const assert = (condition, label) => { if (!condition) throw new Error(label); passed.push(label); };
  const downloads = [];
  const requests = [];
  let failUpload = false;
  page.on('download', download => downloads.push(download.suggestedFilename()));
  await page.route('**/api/submit', async route => {
    requests.push(route.request().postDataBuffer().toString('latin1'));
    await route.fulfill({status:failUpload ? 502 : 200,contentType:'application/json',body:JSON.stringify({ok:!failUpload})});
  });
  await page.goto('http://localhost:5173/');
  await page.setViewportSize({width:390,height:844});
  const shutter = page.locator('.shutter');
  await page.waitForFunction(() => document.querySelector('.shutter')?.disabled === false);
  assert(await page.evaluate(() => window.__testCameraRequests.every(request => request.audio === false)), 'camera requests no microphone');
  assert(await page.evaluate(() => window.__testCameraRequests.at(-1).video.width.ideal === 3840), 'higher camera resolution requested');
  assert(await shutter.evaluate(el => getComputedStyle(el).touchAction === 'none'), 'long hold prevents touch scrolling');
  let bounds = await shutter.boundingBox();
  await page.mouse.move(bounds.x + bounds.width/2,bounds.y + bounds.height/2);
  await page.mouse.down(); await page.waitForTimeout(300); await page.mouse.up();
  await page.waitForURL('**/summary');
  assert(await page.locator('.captured-photo').evaluate(el => el.tagName === 'IMG'), 'short press remains a photo');
  await page.getByRole('button',{name:'Send your wish',exact:true}).click();
  await page.getByText('Sent with love ♡',{exact:true}).waitFor();
  assert(downloads.length === 1 && downloads[0].endsWith('.jpg'), 'successful photo submission automatically downloads JPEG');
  assert(requests.length === 1 && requests[0].includes('name="photo"'), 'photo submits once as photo');
  await page.waitForURL('http://localhost:5173/');
  await page.waitForFunction(() => document.querySelector('.shutter')?.disabled === false);
  bounds = await shutter.boundingBox();
  await page.mouse.move(bounds.x + bounds.width/2,bounds.y + bounds.height/2);
  await page.mouse.down(); await page.waitForTimeout(1300);
  await page.getByRole('button',{name:'Stop recording',exact:true}).waitFor({timeout:10000});
  assert(await page.getByRole('button',{name:'Stop recording',exact:true}).isVisible(), 'holding over one second starts recording');
  assert(await page.getByRole('button',{name:'Switch front and rear cameras'}).isDisabled(), 'camera switch is disabled while recording');
  assert(new URL(page.url()).pathname === '/', 'video does not navigate before release');
  await page.screenshot({path:'output/playwright/recording-mobile.png'});
  await page.waitForTimeout(1000); await page.mouse.up();
  await page.waitForURL('**/summary');
  await page.locator('.captured-photo').evaluate(video => new Promise(resolve => { if (video.readyState >= 1) resolve(); else video.onloadedmetadata=resolve; }));
  assert(await page.locator('.captured-photo').evaluate(video => video.tagName === 'VIDEO' && video.videoHeight <= 1920 && video.videoWidth <= 1920 && video.duration > 0), 'recording is an actual bounded-resolution playable video');
  const wish = page.getByRole('textbox',{name:'Your wedding wish',exact:true});
  await wish.fill('Video wish stays safe ♡');
  for (const scheme of ['light','dark']) {
    await page.emulateMedia({colorScheme:scheme});
    for (const [width,height] of [[375,667],[430,932],[1440,900],[844,390]]) {
      await page.setViewportSize({width,height});
      await page.getByRole('button',{name:'Enlarge video',exact:true}).click();
      const video = page.locator('dialog video');
      await video.waitFor();
      await page.waitForFunction(() => { const video = document.querySelector('dialog video'); return video && video.readyState >= 2 && !video.paused; });
      assert(await video.evaluate(video => video.controls && !video.paused), `${scheme} ${width}: preview autoplays with native controls`);
      await video.evaluate(video => video.pause());
      assert(await video.evaluate(video => video.paused), `${scheme} ${width}: preview pauses`);
      const close = page.getByRole('button',{name:'Close video preview',exact:true});
      const box = await close.boundingBox();
      assert(box.width >= 44 && box.x + box.width <= width && box.y + box.height <= height, `${scheme} ${width}: close is reachable`);
      if (width === 375) await page.screenshot({path:`output/playwright/video-preview-${scheme}.png`});
      await close.click();
      assert(await wish.inputValue() === 'Video wish stays safe ♡', `${scheme} ${width}: closing preview retains wish`);
    }
  }
  failUpload = true;
  await page.getByRole('button',{name:'Send your wish',exact:true}).click();
  await page.getByText(/Your video is still here/).waitFor();
  assert(downloads.length === 1 && await wish.inputValue() === 'Video wish stays safe ♡' && await page.locator('.captured-photo').count() === 1, 'failed video upload keeps video and wish and does not download');
  failUpload = false;
  await page.getByRole('button',{name:'Send your wish',exact:true}).dblclick();
  await page.getByText('Sent with love ♡',{exact:true}).waitFor();
  assert(downloads.length === 2 && /\.(mp4|webm)$/.test(downloads[1]), 'successful video automatically downloads its actual format');
  assert(requests.length === 3 && requests[2].includes('name="video"') && !requests[2].includes('name="photo"'), 'retry uploads video exactly once, not a photo');
  await page.waitForURL('http://localhost:5173/');
  await page.waitForFunction(() => document.querySelector('.shutter')?.disabled === false);
  await page.keyboard.press('Tab');
  await shutter.focus();
  await page.keyboard.down('Space'); await page.waitForTimeout(1300);
  await page.getByRole('button',{name:'Stop recording',exact:true}).waitFor({timeout:10000});
  assert(await page.getByRole('button',{name:'Stop recording',exact:true}).isVisible(), 'keyboard hold also starts recording');
  await page.keyboard.up('Space'); await page.waitForURL('**/summary');
  await page.getByRole('button',{name:'Retake',exact:true}).click();
  await page.waitForURL('http://localhost:5173/');
  await page.waitForFunction(() => document.querySelector('.shutter')?.disabled === false);
  bounds = await shutter.boundingBox();
  await page.mouse.move(bounds.x + bounds.width/2,bounds.y + bounds.height/2);
  await page.mouse.down(); await page.waitForTimeout(1300);
  await page.getByRole('button',{name:'Stop recording',exact:true}).waitFor({timeout:10000});
  await page.dispatchEvent('.shutter','pointercancel'); await page.mouse.up();
  await page.waitForFunction(() => !document.querySelector('.shutter').classList.contains('is-recording'));
  assert(new URL(page.url()).pathname === '/', 'cancelled gesture discards recording safely');
  await page.waitForFunction(() => document.querySelector('.shutter')?.disabled === false);
  bounds = await shutter.boundingBox();
  await page.mouse.move(bounds.x + bounds.width/2,bounds.y + bounds.height/2);
  await page.mouse.down();
  await page.waitForURL('**/summary',{timeout:70000}); await page.mouse.up();
  assert(await page.locator('.captured-photo').evaluate(video => video.tagName === 'VIDEO'), '60-second recording limit automatically opens summary');
  await page.reload(); await page.waitForURL('http://localhost:5173/');
  assert(await page.evaluate(() => localStorage.length === 0 && sessionStorage.length === 0), 'video stays in memory and refresh removes it');
  await page.unroute('**/api/submit');
  return {checks:passed.length,passed,downloads};
}
