async (page) => {
  const results = [];
  const assert = (condition, description) => { if (!condition) throw new Error(description); results.push(description); };
  await page.unrouteAll({ behavior: 'ignoreErrors' });
  await page.goto('http://localhost:5173/summary');
  await page.waitForFunction(() => document.querySelector('.shutter') && !document.querySelector('.shutter').disabled);
  assert(new URL(page.url()).pathname === '/', 'summary entry without memory redirects');
  const shutter = page.getByRole('button', { name: 'Take photo' });
  await page.getByRole('button', { name: 'Switch front and rear cameras' }).click();
  await page.waitForFunction(() => document.querySelector('.shutter') && !document.querySelector('.shutter').disabled);
  assert(await page.evaluate(() => document.querySelector('video').classList.contains('is-mirrored')), 'front preview mirrors');
  assert(await page.evaluate(() => window.__testCameraTracks[0].readyState === 'ended'), 'switch stops previous stream');
  await shutter.click();
  await page.waitForURL('**/summary');
  await page.waitForFunction(() => window.__testCameraTracks.every(track => track.readyState === 'ended'));
  assert(await page.evaluate(() => window.__testCameraTracks.every(track => track.readyState === 'ended')), 'capture navigation stops all camera tracks');
  await page.getByRole('textbox', { name: 'Your wedding wish', exact: true }).fill('Forever happy ❤️');
  let attempts = 0;
  let release;
  const pending = new Promise(resolve => { release = resolve; });
  await page.route('**/api/submit', async route => {
    attempts++;
    if (attempts === 1) await route.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ ok: false, message: 'secret upstream details' }) });
    else if (attempts === 2) await route.fulfill({ status: 429, contentType: 'application/json', body: JSON.stringify({ ok: false, retryAfterSeconds: 2 }) });
    else {
      await pending;
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ ok: true }) });
    }
  });
  const submit = page.getByRole('button', { name: 'Send our wish', exact: true });
  await submit.click();
  await page.getByText('Your photo is still here', { exact: false }).waitFor();
  assert((await page.getByRole('textbox').first().inputValue()) === 'Forever happy ❤️', 'failure retains wish');
  assert(await page.getByAltText('Your captured wedding memory').isVisible(), 'failure retains photo');
  assert(!(await page.locator('main').innerText()).includes('secret upstream'), 'upstream errors stay private');
  await submit.click();
  await page.getByRole('button', { name: 'Try again in 2s' }).waitFor();
  assert(await page.getByRole('button', { name: 'Try again in 2s' }).isDisabled(), 'Telegram cooldown disables retry');
  await submit.waitFor();
  await submit.click();
  await page.getByRole('button', { name: 'Sending with love…' }).waitFor();
  await page.goBack();
  await page.waitForURL('**/summary');
  assert(new URL(page.url()).pathname === '/summary', 'browser Back blocked while sending');
  assert(attempts === 3, 'one active upload despite navigation');
  release();
  await page.getByRole('heading', { name: 'Sent with love ♡' }).waitFor();
  await page.waitForURL('http://localhost:5173/');
  await page.waitForFunction(() => document.querySelector('.shutter') && !document.querySelector('.shutter').disabled);
  assert(await page.evaluate(() => window.__testCameraTracks.filter(track => track.readyState === 'live').length) === 1, 'success starts exactly one fresh stream');
  await shutter.click();
  await page.waitForURL('**/summary');
  assert((await page.getByRole('textbox').first().inputValue()) === '', 'success clears old wish');
  await page.getByRole('textbox').first().fill('Retake draft');
  await page.getByRole('button', { name: 'Retake' }).click();
  await page.waitForFunction(() => document.querySelector('.shutter') && !document.querySelector('.shutter').disabled);
  await shutter.click();
  await page.waitForURL('**/summary');
  assert((await page.getByRole('textbox').first().inputValue()) === '', 'retake clears old wish');
  await page.goBack();
  await page.waitForURL('http://localhost:5173/');
  await page.goForward();
  await page.waitForURL('http://localhost:5173/');
  assert(new URL(page.url()).pathname === '/', 'Back/Forward cannot restore stale summary');
  await page.waitForFunction(() => document.querySelector('.shutter') && !document.querySelector('.shutter').disabled);
  await shutter.click();
  await page.waitForURL('**/summary');
  await page.reload();
  await page.waitForURL('http://localhost:5173/');
  assert(new URL(page.url()).pathname === '/', 'refresh clears summary memory');
  assert(await page.evaluate(() => localStorage.length === 0 && sessionStorage.length === 0), 'no persistent browser draft storage');
  await page.unroute('**/api/submit');
  return { passed: results, attempts };
}
